apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-payment-api
  labels:
    app: ecommerce-payment   # 🔥 agrupa toda la app
    service: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-payment
  template:
    metadata:
      labels:
        app: ecommerce-payment
    spec:
      containers:
        - name: ecommerce-payment
          image: host.docker.internal:5000/ecommerce-payment-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8006
          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/amazon_ecommerce_payment
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              value: postgres
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SCHEMA_REGISTRY
              value: http://schema-registry:8081
