spring.application.name=ecommerce-payment-service
server.port=8006

users.service.url=${USERS_SERVICE_URL:http://localhost:8004}

#Configuracion del datasource y hibernate
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://java-pg-db:5432/Cascaron
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/amazon_ecommerce_payment}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#Configuracion de hibernate (PERMITE LA CREACION DE LAS TABLAS EN LA BBDD PARTIENDO DE LOS MODELOS)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Me deshabilita el devops del microservicio ya q da conflicto con los eventos avro
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
spring.devtools.add-properties=false

#Configuracion kafka shema registry automatica en dependencia del entorno
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.schema-registry=${SCHEMA_REGISTRY:http://localhost:8083}