apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-payment-api
  labels:
    app: ecommerce-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-payment
  template:
    metadata:
      labels:
        app: ecommerce-payment
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: ecommerce-payment
          image: docker.io/drjimenez/myrepodockerhub:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 8006

          # 🔥 AJUSTE CRÍTICO (AQUÍ ESTABA EL PROBLEMA)
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "300m"

          env:
            - name: DB_URL
              value: jdbc:postgresql://postgres:5432/amazon_ecommerce_payment

            - name: DB_USER
              value: postgres

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: db-pass

            # ⚠️ IMPORTANTE: desactiva Kafka por ahora
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: ""

            - name: SCHEMA_REGISTRY
              value: ""

            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: stripe-key

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8006
            initialDelaySeconds: 25
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8006
            initialDelaySeconds: 50
            periodSeconds: 15